export const SET_GIF_SEARCH_PHRASE = "SET_GIF_SEARCH_PHRASE"
export const SET_GIF_SEARCH_RESULT = "SET_GIF_SEARCH_RESULT"
export const SET_WEIRDNESS_LEVEL = "SET_WEIRDNESS_LEVEL"
export const CLEAR_SEARCH_DATA = "CLEAR_SEARCH_DATA"
